hufstudy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('notice/', include('notice.urls')),
    
    path('todolist/', include('tasks.urls'))
]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name="list"),
    path('delete/<str:pk>/', views.deleteTask, name="delete")
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('agreement/', views.AgreementView.as_view(), name='agreement'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('registerauth/', views.register_success, name='register_success'),
    path('activate/<str:uid64>/<str:token>/', views.activate, name='activate'),
    
    path('', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('mypage/', views.mypage_view, name='mypage'),
    path('mypage/update/', views.mypage_update_view, name='mypage_update'),
    path('mypage/delete/', views.mypage_delete_view, name='mypage_delete'),
    path('mypage/password/', views.password_edit_view, name='mypage_password'),







]

users/models.py
from django.db import models
from .choice import *


# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from .choice import *


class UserManager(BaseUserManager):
    def create_user(self, user_id, password, email, hp, name, student_id, grade, department, auth, **extra_fields):

        if not user_id:
            raise ValueError('user_id Required!')
            
        user = self.model(
            user_id = user_id,
            email = email,
            hp = hp,
            name = name,
            student_id = student_id,
            grade = grade,
            department = department,
            auth = auth,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, user_id, password, email=None, hp=None, name=None, student_id=None, grade=None, department=None, auth=None):
        user = self.create_user(user_id, password, email, hp, name, student_id, grade, department, auth)
        user.is_superuser = True
        user.is_staff = True
        user.is_admin = True
        user.level = 0
        user.save(using=self._db)
        return user

class User(AbstractBaseUser, PermissionsMixin):
    
    objects = UserManager()

    user_id = models.CharField(max_length=12, verbose_name="아이디", unique=True)
    password = models.CharField(max_length=256, verbose_name="비밀번호")
    email = models.EmailField(max_length=128, verbose_name="이메일",null=True, unique=True)
    hp = models.IntegerField(verbose_name="핸드폰번호", null=True, unique=True)
    name = models.CharField(max_length=8, verbose_name="이름", null=True)
    student_id = models.IntegerField(max_length=9, verbose_name="학번", null=True)
    grade = models.CharField(choices=GRADE_CHOICES, max_length=18, verbose_name="학년", null=True)
    level = models.CharField(choices=LEVEL_CHOICES, max_length=18, verbose_name="등급", default=3)
    department = models.CharField(choices=DEPARTMENT_CHOICES, max_length=40, verbose_name="학과", null=True)
    auth = models.CharField(max_length=10, verbose_name="인증번호", null=True)
    date_joined = models.DateTimeField(auto_now_add=True, verbose_name='가입일', null=True, blank=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'user_id'
    REQUIRED_FIELDS = ['email']
    
    def __str__(self):
        return self.user_id

    class Meta:
        db_table = "회원목록"
        verbose_name = "사용자"
        verbose_name_plural = "사용자" 

users/forms.py
from django import forms
from django.contrib.auth.hashers import check_password
from django.forms import fields
from .models import User
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, SetPasswordForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from .choice import *


def hp_validator(value):
	if len(str(value)) != 10:
		raise forms.ValidationError('정확한 핸드폰 번호를 입력해주세요.')

def student_id_validator(value):
	if len(str(value)) != 9:
		raise forms.ValidationError('본인의 학번 9자리를 입력해주세요.')



class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        self.fields['user_id'].label = '아이디'
        self.fields['user_id'].widget.attrs.update({
            # 'class': 'form-control col-sm-10',
            'class': 'form-control',
            # 'placeholder': '아이디를 입력해주세요.',
            'autofocus': False
        })
        self.fields['password1'].label = '비밀번호'
        self.fields['password1'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': '비밀번호를 입력해주세요.',
        })
        self.fields['password2'].label = '비밀번호 확인'
        self.fields['password2'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': '비밀번호를 다시 입력해주세요.',
        })
        self.fields['email'].label = '이메일'
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': '회원가입 후 입력하신 메일로 본인인증 메일이 전송됩니다.',
        })
        self.fields['name'].label = '이름'
        self.fields['name'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': "아이디, 비밀번호 찾기에 이용됩니다.",
        })
        self.fields['hp'].label = '핸드폰번호'
        self.fields['hp'].validators = [hp_validator]
        self.fields['hp'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': "'-'를 제외한 숫자로 입력해주세요",
        })
        self.fields['grade'].label = '학년'
        self.fields['grade'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['student_id'].label = '학번'
        self.fields['student_id'].validators = [student_id_validator]
        self.fields['student_id'].widget.attrs.update({
            'class': 'form-control',
            # 'placeholder': "학번을 입력해주세요.",
        })
        self.fields['department'].label = '학과'
        self.fields['department'].widget.attrs.update({
            'class': 'form-control'
        })

    class Meta:
        model = User
        fields = ['user_id', 'password1', 'password2', 'email', 'name', 'hp', 'grade', 'student_id', 'department']

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.level = '2'
        user.is_active = False
        user.save()

        return user


# 로그인 폼

class LoginForm(forms.Form):
    user_id = forms.CharField(
        widget=forms.TextInput(
        attrs={'class': 'form-control',}), 
        error_messages={'required': '아이디을 입력해주세요.'},
        max_length=17,
        label='아이디'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
        attrs={'class': 'form-control',}), 
        error_messages={'required': '비밀번호를 입력해주세요.'},
        label='비밀번호'
    )
    
    def clean(self):
        cleaned_data = super().clean()
        user_id = cleaned_data.get('user_id')
        password = cleaned_data.get('password')

        if user_id and password:
            try:
               user = User.objects.get(user_id=user_id)
            except User.DoesNotExist:
                self.add_error('user_id', '존재하지 않는 아이디입니다.')
                return
            
            if not check_password(password, user.password):
                self.add_error('password', '비밀번호가 틀렸습니다.')

# 마이페이지

from django.contrib.auth.forms import UserChangeForm

class CustomUserChangeForm(UserChangeForm):
    
    hp = forms.IntegerField(label='연락처', widget=forms.NumberInput(
        attrs={'class': 'form-control', 'maxlength':'11', 'oninput':"maxLengthCheck(this)",}), 
    )   
    name = forms.CharField(label='이름', widget=forms.TextInput(
        attrs={'class': 'form-control', 'maxlength':'8',}), 
    )
    student_id = forms.IntegerField(required=False, label='학번', widget=forms.NumberInput(
        attrs={'class': 'form-control', 'maxlength':'9', 'oninput':"maxLengthCheck(this)",}), 
    )   
    grade = forms.ChoiceField(choices=GRADE_CHOICES, label='학년', widget=forms.Select(
        attrs={'class': 'form-control',}), 
    )
    department = forms.ChoiceField(choices=DEPARTMENT_CHOICES, label='학과', widget=forms.Select(
        attrs={'class': 'form-control',}), 
    )
    
    class Meta:
        model = User()
        fields = ['hp','name','student_id', 'grade', 'department']

# 회원탈퇴

from django.contrib.auth.hashers import check_password

class CheckPasswordForm(forms.Form):
    password = forms.CharField(label='비밀번호', widget=forms.PasswordInput(
        attrs={'class': 'form-control',}), 
    )
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = self.user.password
        
        if password:
            if not check_password(password, confirm_password):
                self.add_error('password', '비밀번호가 일치하지 않습니다.')

# 비밀번호 변경

from django.contrib.auth.forms import PasswordChangeForm

class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(CustomPasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].label = '기존 비밀번호'
        self.fields['old_password'].widget.attrs.update({
            'class': 'form-control',
            'autofocus': False,
        })
        self.fields['new_password1'].label = '새 비밀번호'
        self.fields['new_password1'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['new_password2'].label = '새 비밀번호 확인'
        self.fields['new_password2'].widget.attrs.update({
            'class': 'form-control',
        })

users/views.py
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views.generic.base import TemplateView
from .decorators import *
from .models import User 
from django.views.generic import View
from django.contrib import messages
from django.conf import settings

from django.urls import reverse
from .helper import send_mail
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage

# 약관 및 개인정보 동의
@method_decorator(logout_message_required, name='dispatch')
class AgreementView(View):
    def get(self, request, *args, **kwargs):
        request.session['agreement'] = False
        return render(request, 'users/agreement.html')

    def post(self, request, *args, **kwarg):
        if request.POST.get('agreement1', False) and request.POST.get('agreement2', False):
            request.session['agreement'] = True

            if request.POST.get('register') == 'register':       
                return redirect('/register/')
            else:
                return redirect('/register/')
        else:
            messages.info(request, "약관에 모두 동의해주세요.")
            return render(request, 'users/agreement.html')

# 회원가입
from django.core.exceptions import PermissionDenied, ValidationError
from .forms import RegisterForm
from django.views.generic import CreateView
class RegisterView(CreateView):
    model = User
    template_name = 'users/register.html'
    form_class = RegisterForm

    def get(self, request, *args, **kwargs):
        if not request.session.get('agreement', False):
            raise PermissionDenied
        request.session['agreement'] = False
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        self.request.session['register_auth'] = True
        messages.success(self.request, '회원님의 입력한 Email 주소로 인증 메일이 발송되었습니다. 인증 후 로그인이 가능합니다.')
        return reverse('users:register_success')

    def form_valid(self, form):
        self.object = form.save()

        send_mail(
            '[HUFSTUDY] HUFSTUDY 웹사이트 회원가입 인증메일',
            [self.object.email],
            html=render_to_string('users/register_email.html', {
                'user': self.object,
                'uid': urlsafe_base64_encode(force_bytes(self.object.pk)).encode().decode(),
                'domain': self.request.META['HTTP_HOST'],
                'token': default_token_generator.make_token(self.object),
            }),
        )
        return redirect(self.get_success_url())

def activate(request, uid64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uid64))
        current_user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist, ValidationError):
        messages.error(request, '메일 인증에 실패했습니다.')
        return redirect('users:login')

    if default_token_generator.check_token(current_user, token):
        current_user.is_active = True
        current_user.save()

        messages.info(request, '메일 인증이 완료 되었습니다. 회원가입을 축하드립니다!')
        return redirect('users:login')

    messages.error(request, '메일 인증에 실패했습니다.')
    return redirect('users:login')

def register_success(request):
    if not request.session.get('register_auth', False):
        raise PermissionDenied
    request.session['register_auth'] = False

    return render(request, 'users/register_success.html')

# 로그인
from .forms import LoginForm
from django.contrib.auth import login, authenticate
from django.views.generic import FormView
from notice.models import Notice

class LoginView(FormView):
    
    template_name = 'users/home.html'
    form_class = LoginForm
    success_url = '/'

    def form_valid(self, form):
        user_id = form.cleaned_data.get("user_id")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=user_id, password=password)
        
        if user is not None:
            self.request.session['user_id'] = user_id
            login(self.request, user)

        return super().form_valid(form)
    
def main_view(request):
    notice_list = Notice.objects.order_by('-id')[:5]
    context = {
        'notice_list' : notice_list,
    }
    return render(request, 'users/home.html', context)


# 로그아웃
from django.contrib.auth import logout

def logout_view(request):
    logout(request)
    return redirect('/')

# 마이페이지


@login_message_required
def mypage_view(request):
    if request.method == 'GET':
        return render(request, 'users/mypage.html')





from .forms import CustomUserChangeForm

@login_message_required
def mypage_update_view(request):
    if request.method == 'POST':
        user_change_form = CustomUserChangeForm(request.POST, instance=request.user)

        if user_change_form.is_valid():
            user_change_form.save()
            messages.success(request, '회원정보가 수정되었습니다.')
            return render(request, 'users/mypage.html')

    else:
        user_change_form = CustomUserChangeForm(instance = request.user)

        return render(request, 'users/mypage_update.html', {'user_change_form':user_change_form})
       
#회원탈퇴

from .forms import CheckPasswordForm

@login_message_required
def mypage_delete_view(request):
    if request.method == 'POST':
        password_form = CheckPasswordForm(request.user, request.POST)
        
        if password_form.is_valid():
            request.user.delete()
            logout(request)
            messages.success(request, "회원탈퇴가 완료되었습니다.")
            return redirect('/')
    else:
        password_form = CheckPasswordForm(request.user)

    return render(request, 'users/mypage_delete.html', {'password_form':password_form})


#비밀번호 변경

from .forms import CustomPasswordChangeForm
from django.contrib.auth import update_session_auth_hash

@login_message_required
def password_edit_view(request):
    if request.method == 'POST':
        password_change_form = CustomPasswordChangeForm(request.user, request.POST)
        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "비밀번호가 변경되었습니다.")
            return redirect('users:mypage')
    else:
        password_change_form = CustomPasswordChangeForm(request.user)

    return render(request, 'users/mypage_password.html', {'password_change_form':password_change_form})

templates/users/mypage.html
{% extends "users/mypage_base.html" %}

{% block mobileView %}
<meta name="viewport" content="width=570, user-scalable=yes">
{% endblock %}

{% block contents %}

    {% load static %}
    <div id="jb-container">
        <div id="jb-header1">
            <img src="{%static 'img/users/logotop.png' %}" style="width: 1530px; height: 70px;">
            <button class="btn1" type="button" onclick="location.href='/'" style="opacity: 0;">버튼1</button>
        </div>

        <div id="jb-container2">
            <div id="jb-container2-content">
                <div class="" style="font-size:0.8em;">
                    <br>
                </div>
                <h5 style="margin: 0px; font-size: 1.5rem; font-family: '양진체';">&nbsp&nbsp&nbspMY PROFILE</h5>
            </div>
            <div id="jb-container2-content2">
                <table>
                    <div class="" style="font-size:0.8em;">
                        <br>
                    </div>
                    <tr>
                        <td>&nbsp&nbsp아이디:</td>
                        {% if user.level == '0'%}
                        <td>&nbsp{{ user.user_id }}(개발자)</td>
                        {% elif user.level == '1' %}
                        <td>&nbsp{{ user.user_id }}(관리자)</td>
                        {% else %}  
                        <td>&nbsp{{ user.user_id }}</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>&nbsp&nbsp이메일:</td>
                        <td>&nbsp{{ user.email }}</td>
                    </tr>
                    <tr>
                        <td>&nbsp&nbsp이름:</td>
                        <td>&nbsp{{ user.name }}</td>
                    </tr>
                    <tr>
                        <td>&nbsp&nbsp연락처:</td>
                        <td>&nbsp{{ user.hp }}</td>
                    </tr>
                    <tr>
                        <td>&nbsp&nbsp학번:</td>
                        <td>&nbsp{{ user.student_id }}</td>
                    </tr>
                    <tr>
                        <td>&nbsp&nbsp학년:</td>
                        <td>&nbsp{{ user.grade }}</td>
                    </tr>
                    <tr>
                        <td>&nbsp&nbsp학과:</td>
                        <td>&nbsp{{ user.department }}</td>

                        
                    </tr>
                    
                </table>
                <div class="" style="font-size:0.8em;">
                    <br>
                </div>
                &nbsp&nbsp&nbsp&nbsp
                <a href="{% url 'users:mypage_update' %}" class="btn btn-purple" style="font-family: 'paybooc-Bold';">프로필 수정</a>
                <a href="{% url 'users:mypage_password' %}" class="btn btn-purple" style="font-family: 'paybooc-Bold'; width: 120px;">비밀번호 변경</a>
                <a href="{% url 'users:mypage_delete' %}" class="btn btn-red" style="font-family: 'paybooc-Bold';">회원탈퇴</a>
            </div>
            <div id="jb-container2-content3">
                <h1 style="font-size: 0.6em; color: #8C8C8C;">
                    <br><br><br>
                    &nbsp&nbsp더 나은 HUFSTUDY 사용을 위해 부탁드려요!</h1>
            </div>

        </div>
        <div id="jb-content2">
            <br>
            <h5 style="margin: 0px; font-size: 1.8rem; font-family: '양진체'; text-align: center;">Time Table</h5>
            
        </div>
        <div id="jb-content3">
            <br>
            <h5 style="margin: 0px; font-size: 1.8rem; font-family: '양진체'; text-align: center;">To Do List</h5>

        </div>

        <div class="btn-group" role="group" style="position: absolute; left:100px; top:585px;">
            <button class="btn btn-secondary" type="button">
                오류 신고
            </button> 
            <button class="btn btn-secondary" type="button" style="width: 158px;">
                ABOUT HUFSTUDY
            </button>
        </div>

    </div>
    {% endblock %}

templates/users/mypage_base.html
<!doctype html>
<html lang="ko">
    
    <head>


        <meta charset="utf-8">
        <title>HUFSTUDY</title>
        {% block mobileView %}
        {% endblock %}
    
    
        {% load static %}
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
        <!-- Bootstrap v5.0-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/users/style.css' %}?after">
    
        
    
    
    
        <style>
    
        button.btn1 {
          position: absolute;
          top: 1px;
          left : 10px;
          width: 270px;
          height: 68px;
        }
    
          #jb-container {
            width: 1530px;
            height: 760px;
          }
    
          #jb-header1 {
            width: 1530px;
            height: 70px;
            position : relative;
          }
          #jb-container2 {
            width: 400px;
            height: 410px;
            float: left;
            border: 1px solid #bcbcbc;
            box-shadow: 1.5px 1.5px 4.5px 1.5px #dadce0;
            margin-top: 100px;
            margin-left: 100px;
            border-radius: 8px;
          }
    
          #jb-container2-content {
          width: 400px;
          height: 60px;
          background-color: #F7F7F7;
          border-top-right-radius: 8px;
          border-top-left-radius: 8px;
          border-bottom:1px solid #bcbcbc;
          }
    
          #jb-container2-content2 {
          width: 400px;
          height: 290px;
          background-color: #ffffff;
          }
    
          #jb-container2-content3 {
          width: 400px;
          height: 60px;
          background-color: #F7F7F7;
          border-bottom-right-radius: 8px;
          border-bottom-left-radius: 8px;
          border-top:1px solid #bcbcbc;
          }
    
          #jb-content2 {
            background-color:#D4F4FA;
            margin-top: 50px;
            width: 500px;
            height: 650px;
            float: left;
            border: 1px solid #bcbcbc;
            margin-left: 75px;
          }
    
          #jb-content3 {
            background-color: #DFCAE7;
            margin-top: 50px;
            width: 400px;
            height: 650px;
            float: left;
            border: 1px solid #bcbcbc;
            margin-left: 25px;
          }
        </style>
      </head>

<body style="background-color: #f7f7ff;">
    
    {% block contents %}
    {% endblock %}
    

    {% if messages %}
    {% for message in messages %}
    {% if message.tags %}
    <script>
        alert("{{ message.message }}")
    </script>
    {% endif %}
    {% endfor %}
    {% endif %}
</body>

</html>

templates/users/mypage_delete.html
{% extends "users/mypage_base.html" %}

{% block mobileView %}
<meta name="viewport" content="width=570, user-scalable=yes">
{% endblock %}

{% block contents %}

    {% load static %}
    <div id="jb-container">
        <div id="jb-header1">
            <img src="{%static 'img/users/logotop.png' %}" style="width: 1530px; height: 70px;">
            <button class="btn1" type="button" onclick="location.href='/'" style="opacity: 0;">버튼1</button>
        </div>

        <div id="jb-container2">
            <div id="jb-container2-content">
                <div class="" style="font-size:0.8em;">
                    <br>
                </div>
                <h5 style="margin: 0px; font-size: 1.5rem; font-family: '양진체';">&nbsp&nbsp&nbspMY PROFILE</h5>
            </div>
            <div id="jb-container2-content2">
                <form method="POST" novalidate>
                    {% csrf_token %}
                    <p style="padding-inline: 30px;"><br><strong>{{ user.user_id }}</strong> 님의 계정이 삭제됩니다.<br>탈퇴시 개인정보 및 이용정보가 삭제되며 복구할 수 없습니다. 비밀번호를 입력한 후 하단의 유의사항 확인에 체크해주세요.</p>
                    <table>
                        <tr>
                        <td>
                            &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp비밀번호:&nbsp&nbsp
                        </td>
                        <td>
                        {{ password_form.password }}
                        {% if password_form.password.errors %}
                        <script type="text/javascript">
                            document.getElementsByName('password')[0].setAttribute('class', 'form-control is-invalid')
                        </script>
                        {% for error in password_form.password.errors %}
                        <div class="invalid-feedback">
                            <small>{{ error }}</small>
                        </div>
                        {% endfor %}
                        {% else %}
                        <br>
                        {% endif %}
                        </td>
                        </tr>
                    </table>
                    &nbsp&nbsp&nbsp&nbsp&nbsp
                    <input type="checkbox" name="ck" onClick="checkDisable(this.form)">
                    <span>유의사항을 확인했고, 이에 동의합니다.</span>
                    <div class="" style="font-size:0.1em;">
                        <br>
                    </div>
                    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                    <a href="{% url 'users:mypage' %}" class="btn btn-purple" style="font-family: 'paybooc-Bold';">탈퇴취소</a>
                    &nbsp&nbsp&nbsp&nbsp
                    <button type="submit" name= "bt" disabled="true" class="btn btn-red" style="font-family: 'paybooc-Bold';">회원탈퇴</button>

                </form>
            </div>
            <div id="jb-container2-content3">
                <h1 style="font-size: 0.6em; color: #8C8C8C;">
                    <br><br><br>
                    &nbsp&nbsp더 나은 HUFSTUDY 사용을 위해 부탁드려요!</h1>
            </div>

        </div>
        <div id="jb-content2">
            <br>
            <h5 style="margin: 0px; font-size: 1.8rem; font-family: '양진체'; text-align: center;">Time Table</h5>
            
        </div>
        <div id="jb-content3">
            <br>
            <h5 style="margin: 0px; font-size: 1.8rem; font-family: '양진체'; text-align: center;">To Do List</h5>

        </div>

        <div class="btn-group" role="group" style="position: absolute; left:100px; top:585px;">
            <button class="btn btn-secondary" type="button">
                오류 신고
            </button> 
            <button class="btn btn-secondary" type="button" style="width: 158px;">
                ABOUT HUFSTUDY
            </button>
        </div>

    </div>

    <script type="text/javascript">
        function checkDisable(form) {
            if (form.ck.checked == true) {
                form.bt.disabled = false;
            } else {
                form.bt.disabled = true;
            }
        }
    </script>
    {% endblock %}

templates/users/register_email.html
{% autoescape off %}
<!DOCTYPE html>
<html>
<body>
    {% load static %}
    <div style="width:100%;min-width:100%;height:100%;">
        <div style="padding: 70px 0; background: #f7f8f9;">
            <div style="margin: 0 auto; width: 600px; color: #000;">
                <div style="padding: 30px 90px; text-align: center; border: 1px solid #dfdfdf; background: #fff;">
                    <h3 style="margin-bottom: 35px; font-size: 30px; font-weight: 600;">회원가입 인증 메일</h3>
                    <div style="padding: 10px 0 20px; border-top: 1px solid rgb(172, 172, 172);">
                        <p style="font-size: 14px; font-weight: 600; line-height: 20px;">HUFSTUDY에 오신 것을 환영합니다!<br>아래 링크를 클릭하시면 회원가입이 완료됩니다.</p>
                    </div>
                    <div style="padding: 20px 30px; background: #f7f8f9;"><a style="font-size: 18px; font-weight: bold;" href="http://{{ domain }}{% url 'users:activate' uid64=uid token=token %}">인증하기</a></div>
                    <div style="padding: 10px 0 20px; border-top: 1px solid rgb(172, 172, 172);">
                        <p style="font-size: 12px; font-weight: 600; line-height: 20px; color: rgba(40, 43, 43, 0.616);">가입을 신청하지 않았는데 이 메일을 받으셨다면 무시하셔도 됩니다.<br>인증 없이 귀하의 이메일 주소는 사용되지 않습니다.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
{% endautoescape %}