hufstudy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('notice/', include('notice.urls')),
    
    path('todolist/', include('tasks.urls'))
]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name="list"),
    path('delete/<str:pk>/', views.deleteTask, name="delete")
]

tasks/models.py
from django.db import models

# Create your models here.

from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=200)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

tasks/forms.py
from django import forms
from django.forms import ModelForm

from .models import *


class TaskForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Add new task...'}))

    class Meta:
        model = Task
        fields = '__all__'

tasks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .models import *
from .forms import *


# Create your views here.

def index(request):
    tasks = Task.objects.all()

    form = TaskForm()

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/todolist/')

    context = {'tasks': tasks, 'form': form}
    return render(request, 'tasks/list.html', context)

def deleteTask(request, pk):
    item = Task.objects.get(id=pk)

    if request.method == 'POST':
        item.delete()
        return redirect('/todolist/')

    context = {'item': item}
    return render(request, 'tasks/delete.html', context)    

templates/tasks/delete.html
<head>
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
    />

    <style>
        .app-container {
            height: 100vh;
            width: 100%;
            background-color: #202124;
        }

        .complete {
            text-decoration: line-through;
        }
    </style>
</head>
</head>

<div class="app-container d-flex align-items-center justify-content-center flex-column">
    <h2 style="text-align: center; color: white">Are you sure you want to delete "{{ item }}"?</h2>


    <div class="row">
        <div class="col-sm-12 text-center">
            <form method="POST" action="">
                {% csrf_token %}
                <button type="submit" id="Confirm" class="btn btn-danger">Delete</button>

                <button type="button" class="btn btn-secondary" href="{% url 'tasks:list' %}">
                    <a href="{% url 'tasks:list' %}" style="color:white">Cancel</a>
                </button>
            </form>


        </div>
    </div>
</div>

templates/tasks/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.9/angular.min.js"></script>
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
    />

    <style>
        .app-container {
            height: 100vh;
            width: 100%;
        }

        .complete {
            text-decoration: line-through;
        }
    </style>

</head>
<body>
<div
        class="app-container d-flex align-items-center justify-content-center flex-column"
        ng-app="myApp"
        ng-controller="myController"
>
    <h3>Todo App</h3>
    <div class="d-flex align-items-center mb-3">

        <div class="form-group mr-3 mb-0">
            <form class="form-inline" method="POST" action="/todolist/">
                {% csrf_token %}

                <div style="display: flex; margin-bottom: 1px">
                    {{ form.title }}

                    &nbsp;

                    <button
                            type="submit"
                            class="btn btn-primary mb-2"
                            ng-click="saveTask()"
                            style="margin-top: 8px;"
                    >
                        Save
                    </button>
                </div>

            </form>
        </div>
    </div>

    <div class="table-wrapper" style="overflow: auto; height: 250px">

        <table class="table table-hover table-bordered">
            <thead>
            <tr>
                <th>No.</th>
                <th>Todo item</th>
                <th>Actions</th>
            </tr>
            </thead>
            {% for task in tasks %}
                <tbody>
                <tr>
                    <td>
                        {{ task.id }}
                    </td>
                    <td>
                        {% if task.complete == True %}
                            <span style="text-decoration: line-through;">{{ task }}</span>
                        {% else %}
                            <span>{{ task }}</span>
                        {% endif %}
                    </td>
                    <td>
                        <a class="btn btn-sm btn-info">Update</a>
                        <a class="btn btn-sm btn-danger" href="{% url 'tasks:delete' task.id %}">Delete</a>
                    </td>
                </tr>
                </tbody>
            {% endfor %}
        </table>
    </div>
</div>
</body>
</html>